OBJECT_NAMES = {
    "sofa",
    "chair",
    "table",
    "desk",
    "lamp",
    "bed",
    "pillow",
    "blanket",
    "cushion",
    "curtain",
    "rug",
    "carpet",
    "mirror",
    "clock",
    "television",
    "remote",
    "book",
    "magazine",
    "shelf",
    "cabinet",
    "drawer",
    "cupboard",
    "wardrobe",
    "hanger",
    "shoe rack",
    "doormat",
    "painting",
    "vase",
    "plant",
    "flowerpot",
    "photo frame",
    "calendar",
    "notebook",
    "pen",
    "pencil",
    "eraser",
    "sharpener",
    "ruler",
    "stapler",
    "paper clip",
    "folder",
    "binder",
    "whiteboard",
    "marker",
    "blackboard",
    "chalk",
    "scissors",
    "glue",
    "tape",
    "envelope",
    "stamp",
    "computer",
    "laptop",
    "keyboard",
    "mouse",
    "monitor",
    "printer",
    "scanner",
    "router",
    "modem",
    "tablet",
    "smartphone",
    "charger",
    "power strip",
    "extension cord",
    "battery",
    "light bulb",
    "fan",
    "heater",
    "air conditioner",
    "radiator",
    "thermostat",
    "door",
    "window",
    "lock",
    "key",
    "handle",
    "doorbell",
    "switch",
    "socket",
    # "plug",
    # "curtain rod",
    # "blinds",
    # "bedside table",
    # "headboard",
    # "mattress",
    # "bedsheet",
    # "duvet",
    # "comforter",
    # "alarm clock",
    # "lamp shade",
    # "wardrobe mirror",
    # "closet",
    # "hanger hook",
    # "laundry basket",
    # "iron",
    # "ironing board",
    # "clothesline",
    # "washing machine",
    # "dryer",
    # "vacuum cleaner",
    # "broom",
    # "dustpan",
    # "mop",
    # "bucket",
    # "cleaning spray",
    # "sponge",
    # "rag",
    # "trash can",
    # "recycling bin",
    # "toilet",
    # "sink",
    # "bathtub",
    # "shower",
    # "towel",
    # "soap",
    # "shampoo",
    # "toothbrush",
    # "toothpaste",
    # "razor",
    # "toilet paper",
    # "mirror cabinet",
    # "toilet brush",
    # "plunger",
    # "bath mat",
    # "hair dryer",
    # "comb",
    # "hairbrush",
    # "cotton swab",
    # "deodorant",
    # "toilet seat",
    # "toilet lid",
    # "hand sanitizer",
    # "air freshener",
    # "medicine cabinet",
    # "first aid kit",
    # "scale",
    # "shaving cream",
    # "makeup kit",
    # "perfume",
    # "tissue box",
    # "cotton pad",
    # "tooth floss",
    # "cup",
    # "glass",
    # "plate",
    # "bowl",
    # "spoon",
    # "fork",
    # "knife",
    # "napkin",
    # "straw",
    # "cutting board",
    # "frying pan",
    # "pot",
    # "saucepan",
    # "baking tray",
    # "oven",
    # "microwave",
    # "stove",
    # "toaster",
    # "kettle",
    # "blender",
    # "mixer",
    # "juicer",
    # "coffee maker",
    # "espresso machine",
    # "fridge",
    # "freezer",
    # "dishwasher",
    # "measuring cup",
    # "colander",
    # "strainer",
    # "whisk",
    # "spatula",
    # "ladle",
    # "rolling pin",
    # "can opener",
    # "peeler",
    # "grater",
    # "knife sharpener",
    # "tray",
    # "placemat",
    # "coaster",
    # "salt shaker",
    # "pepper grinder",
    # "sugar bowl",
    # "butter dish",
    # "bread box",
    # "fruit bowl",
    # "snack jar",
    # "water bottle",
    # "lunch box",
    # "food container",
    # "plastic wrap",
    # "aluminum foil",
    # "oven mitt",
    # "apron",
    # "dish rack",
    # "tea towel",
    # "cupboard handle",
    # "pan lid",
    # "measuring spoon",
    # "timer",
    # "recipe book",
    # "high chair",
    # "baby bottle",
    # "bib",
    # "pacifier",
    # "toy box",
    # "stuffed animal",
    # "building blocks",
    # "board game",
    # "puzzle",
    # "crayons",
    # "coloring book",
    # "doll",
    # "ball",
    # "toy car",
    # "lego set",
    # "train set",
    # "action figure",
    # "teddy bear",
    # "yo-yo",
    # "kite",
    # "skipping rope",
    # "storybook",
    # "drawing pad",
    # "chalkboard",
    # "craft glue",
    # "glitter",
    # "paintbrush",
    # "easel",
    # "canvas",
    # "paint palette",
    # "poster",
    # "wall clock",
    # "floor lamp",
    # "desk lamp",
    # "ceiling light",
    # "chandelier",
    # "wall sconce",
    # "night light",
    # "spotlight",
    # "extension plug",
    # "smart bulb",
    # "speaker",
    # "soundbar",
    # "microphone",
    # "headphones",
    # "earphones",
    # "remote control",
    # "game console",
    # "joystick",
    # "DVD player",
    # "Blu-ray player",
    # "radio",
    # "turntable",
    # "CD",
    # "vinyl record",
    # "projector",
    # "screen",
    # "camera",
    # "tripod",
    # "memory card",
    # "flash drive",
    # "external hard drive",
    # "printer paper",
    # "ink cartridge",
    # "envelope opener",
    # "letter tray",
    # "filing cabinet",
    # "office chair",
    # "desk organizer",
    # "sticky notes",
    # "calendar stand",
    # "calculator",
    # "paper cutter",
    # "whiteboard eraser",
    # "push pin",
    # "bulletin board",
    # "clipboard",
    # "name tag",
    # "business card holder",
    # "filing box",
    # "staple remover",
    # "tape dispenser",
    # "hole punch",
    # "pen holder",
    # "mouse pad",
    # "USB hub",
    # "phone stand",
    # "monitor stand",
    # "document scanner",
    # "keyboard tray",
    # "postcard",
    # "stamp pad",
    # "ribbon",
    # "gift box",
    # "wrapping paper",
    # "scotch tape",
    # "gift bag",
    # "balloon",
    # "party hat",
    # "birthday candle",
    # "banner",
    # "confetti",
    # "cake stand",
    # "serving tray",
    # "snack plate",
    # "ice bucket",
    # "wine glass",
    # "beer mug",
    # "champagne flute",
    # "cocktail shaker",
    # "shot glass",
    # "bottle opener",
    # "corkscrew",
    # "serving spoon",
    # "tablecloth",
    # "napkin holder",
    # "chair cushion",
    # "floor cushion",
    # "bean bag",
    # "footrest",
    # "stool",
    # "bench",
    # "dining table",
    # "coffee table",
    # "side table",
    # "console table",
    # "bookshelf",
    # "tv stand",
    # "media unit",
    # "dresser",
    # "nightstand",
    # "vanity table",
    # "mirror stand",
    # "wardrobe closet",
    # "chest of drawers",
    # "pantry shelf",
    # "shoe cabinet",
    # "umbrella stand",
    # "coat rack",
    # "hat stand",
    # "wall hook",
    # "storage box",
    # "plastic bin",
    # "basket",
    # "crate",
    # "trunk",
    # "safe",
    # "filing safe",
    # "fire extinguisher",
    # "smoke detector",
    # "carbon monoxide alarm",
    # "security camera",
    # "door chain",
    # "alarm panel",
    # "intercom",
    # "key holder",
    # "mailbox",
    # "umbrella",
    # "doorknob",
    # "keychain",
    # "welcome mat",
    # "houseplant",
    # "succulent",
    # "terrarium",
    # "bonsai",
    # "flower vase",
    # "watering can",
    # "plant pot",
    # "soil bag",
    # "garden trowel",
    # "spray bottle",
    # "gardening gloves",
    # "seed packet",
}
